# 作業目標
* 熟悉陣列維度轉換，並且會擷取需要資料

# 作業重點
* 使用 reshape 須注意 order 用法
* where 可以運用邏輯條件擷取資料

---
## 題目:
1. 將下列陣列 array1，轉成維度為 5X6 的 array，順序按列填充。(hint:order="F")
2. 呈上題的 array，找出被 6 除餘 1 的數的索引

In [1]:
import numpy as np

In [8]:
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按 row 填充。(hint:order="F")
array1 = np.array(range(30))

In [9]:
array1.reshape((5, 6), order='C')  # 順序按照 column 填充

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [17]:
order_arr = array1.reshape((5, 6), order='F')
order_arr  # 原陣列不會被取代，記得建立一個新的

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

In [18]:
#2.呈上題的 array，找出被 6 除餘 1 的數的索引
np.where(order_arr % 6 == 1)

(array([0, 1, 2, 3, 4]), array([5, 0, 1, 2, 3]))