# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


* `list()` 只會轉第一個維度（第一層）

* `tolist()` 才會將所有維度的元素轉換成 list

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [1]:
# 記得先 Import 正確的套件

import numpy as np

In [7]:
a = np.random.randint(10, size=6) 
print(a)
print(a.ndim)
print(a.shape)
print(len(a))
print(a.dtype)
print(a.itemsize)
print(a.size)
print(type(a))

[1 6 8 6 7 2]
1
(6,)
6
int64
8
6
<class 'numpy.ndarray'>


In [9]:
b = np.random.randint(10, size=(3,4)) 

print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))

[[0 9 5 6]
 [3 3 8 6]
 [1 1 9 6]]
2
(3, 4)
12
int64
8
3
<class 'numpy.ndarray'>


In [10]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

[[[4 6]
  [1 1]
  [3 4]]

 [[1 2]
  [0 9]
  [2 7]]]
3
(2, 3, 2)
12
int64
8
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [11]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))

[1, 2, 1, 4, 2, 9]
[1, 2, 1, 4, 2, 9]


In [12]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[4, 3, 5, 9], [1, 0, 9, 0], [3, 0, 1, 7]]
[array([4, 3, 5, 9]), array([1, 0, 9, 0]), array([3, 0, 1, 7])]


In [13]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[9, 5], [3, 9], [3, 1]], [[2, 1], [0, 3], [9, 0]]]
[array([[9, 5],
       [3, 9],
       [3, 1]]), array([[2, 1],
       [0, 3],
       [9, 0]])]


In [ ]:
def tolist(iterable):
    '''
    Your Code
    '''

print(tolist(a))
print(tolist(b))
print(tolist(c))

[7, 6, 7, 3, 7, 5]
[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]


In [18]:
def tolist(iterable):
    result = []
    if iterable.ndim == 1:
        return list(iterable)
    elif iterable.ndim == 2:
        for i in iterable:
            result.append(list(i))
        return result
    else:
        for i in iterable:
            for j in i:
                result.append(list(j))
        return result
        
print(tolist(a))
print(tolist(b))
print(tolist(c))

[1, 2, 1, 4, 2, 9]
[[4, 3, 5, 9], [1, 0, 9, 0], [3, 0, 1, 7]]
[[9, 5], [3, 9], [3, 1], [2, 1], [0, 3], [9, 0]]
