## 作業目標:
在array中，可以靈活應用索引幫助資料擷取


## 作業重點:
陣列的索引、切片、以及屬性，皆需要注意使用方式<br>
陣列之中索引式由 0 開始請同學注意

---
## 題目:
1. 生成一個等差數列，首數為 0，尾數為 20，公差為 1 的數列。<br>
2. 呈 1，將以上數列取出偶數。<br>
3. 呈 1，將數列取出 3 的倍數。<br>

In [1]:
import numpy as np

In [2]:
# 1.生成一個等差數列，首數為 0，尾數為 20，公差為 1 的數列
n = np.arange(21)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [8]:
# 2. 呈 1，將以上數列取出偶數
n[2::2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
# 3. 呈 1，將數列取出 3 的倍數
n[3::3]

array([ 3,  6,  9, 12, 15, 18])